import "./globals.css";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Inter } from "next/font/google";
import { getTheme, ThemeName } from "../../styled-system/themes";
import { css } from "../../styled-system/css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const store = cookies();
  const themeName = (store.get("theme")?.value ?? "primary") as ThemeName;
  const theme = themeName && (await getTheme(themeName));

  return (
    <html lang="en" data-panda-theme={themeName ? themeName : undefined}>
      {themeName && (
        <head>
          <style
            type="text/css"
            id={theme.id}
            dangerouslySetInnerHTML={{ __html: theme.css }}
          />
        </head>
      )}
      <body className={css({ bg: "bodyBg" })}>{children}</body>
    </html>
  );
}
